package presentacion.vista;

public enum Evento {
	// Empleado
	ALTA_EMPLEADO, RES_ALTA_EMPLEADO_OK, RES_ALTA_EMPLEADO_KO,

	BAJA_EMPLEADO, RES_BAJA_EMPLEADO_OK, RES_BAJA_EMPLEADO_KO,

	MODIFICAR_EMPLEADO, RES_MODIFICAR_EMPLEADO_OK, RES_MODIFICAR_EMPLEADO_KO,

	BUSCAR_EMPLEADO, RES_BUSCAR_EMPLEADO_OK, RES_BUSCAR_EMPLEADO_KO,

	MOSTRAR_TODOS_EMPLEADOS, RES_MOSTRAR_TODOS_EMPLEADOS_OK, RES_MOSTRAR_TODOS_EMPLEADOS_KO,

	// Cliente
	ALTA_CLIENTE, RES_ALTA_CLIENTE_OK, RES_ALTA_CLIENTE_KO,

	BAJA_CLIENTE, RES_BAJA_CLIENTE_OK, RES_BAJA_CLIENTE_KO,

	MODIFICAR_CLIENTE, RES_MODIFICAR_CLIENTE_OK, RES_MODIFICAR_CLIENTE_KO,

	BUSCAR_CLIENTE, RES_BUSCAR_CLIENTE_OK, RES_BUSCAR_CLIENTE_KO,

	MOSTRAR_TODOS_CLIENTES, RES_MOSTRAR_TODOS_CLIENTES_OK, RES_MOSTRAR_TODOS_CLIENTES_KO,

	// Almacen
	ALTA_ALMACEN, RES_ALTA_ALMACEN_OK, RES_ALTA_ALMACEN_KO,

	BAJA_ALMACEN, RES_BAJA_ALMACEN_OK, RES_BAJA_ALMACEN_KO,

	MODIFICAR_ALMACEN, RES_MODIFICAR_ALMACEN_OK, RES_MODIFICAR_ALMACEN_KO,

	BUSCAR_ALMACEN, RES_BUSCAR_ALMACEN_OK, RES_BUSCAR_ALMACEN_KO,

	MOSTRAR_TODOS_ALMACENES, RES_MOSTRAR_TODOS_ALMACENES_OK, RES_MOSTRAR_TODOS_ALMACENES_KO,

	VINCULAR_PRODUCTO_ALMACEN, RES_VINCULAR_PRODUCTO_ALMACEN_OK, RES_VINCULAR_PRODUCTO_ALMACEN_KO,

	DESVINCULAR_PRODUCTO_ALMACEN, RES_DESVINCULAR_PRODUCTO_ALMACEN_OK, RES_DESVINCULAR_PRODUCTO_ALMACEN_KO,

	// Proveedor
	ALTA_PROVEEDOR, RES_ALTA_PROVEEDOR_OK, RES_ALTA_PROVEEDOR_KO,

	BAJA_PROVEEDOR, RES_BAJA_PROVEEDOR_OK, RES_BAJA_PROVEEDOR_KO,

	MODIFICAR_PROVEEDOR, RES_MODIFICAR_PROVEEDOR_OK, RES_MODIFICAR_PROVEEDOR_KO,

	BUSCAR_PROVEEDOR, RES_BUSCAR_PROVEEDOR_OK, RES_BUSCAR_PROVEEDOR_KO,

	MOSTRAR_TODOS_PROVEEDORES, RES_MOSTRAR_TODOS_PROVEEDORES_OK, RES_MOSTRAR_TODOS_PROVEEDORES_KO,

	MOSTRAR_PROVEEDORES_POR_PRODUCTO, RES_MOSTRAR_PROVEEDORES_POR_PRODUCTO_OK, RES_MOSTRAR_PROVEEDORES_POR_PRODUCTO_KO,

	VINCULAR_PRODUCTO_PROVEEDOR, RES_VINCULAR_PRODUCTO_PROVEEDOR_OK, RES_VINCULAR_PRODUCTO_PROVEEDOR_KO,

	DESVINCULAR_PRODUCTO_PROVEEDOR, RES_DESVINCULAR_PRODUCTO_PROVEEDOR_OK, RES_DESVINCULAR_PRODUCTO_PROVEEDOR_KO,

	// Producto
	ALTA_PRODUCTO, RES_ALTA_PRODUCTO_OK, RES_ALTA_PRODUCTO_KO,

	BAJA_PRODUCTO, RES_BAJA_PRODUCTO_OK, RES_BAJA_PRODUCTO_KO,

	MODIFICAR_PRODUCTO, RES_MODIFICAR_PRODUCTO_OK, RES_MODIFICAR_PRODUCTO_KO,

	BUSCAR_PRODUCTO, RES_BUSCAR_PRODUCTO_OK, RES_BUSCAR_PRODUCTO_KO,

	MOSTRAR_TODOS_PRODUCTOS, RES_MOSTRAR_TODOS_PRODUCTOS_OK, RES_MOSTRAR_TODOS_PRODUCTOS_KO,

	MOSTRAR_PRODUCTOS_POR_PROVEEDOR, RES_MOSTRAR_PRODUCTOS_POR_PROVEEDOR_OK, RES_MOSTRAR_PRODUCTOS_POR_PROVEEDOR_KO,

	MOSTRAR_PRODUCTOS_POR_ALMACEN, RES_MOSTRAR_PRODUCTOS_POR_ALMACEN_OK, RES_MOSTRAR_PRODUCTOS_POR_ALMACEN_KO,

	// Venta

	ALTA_VENTA, RES_ALTA_VENTA_OK, RES_ALTA_VENTA_KO,

	BAJA_VENTA, RES_BAJA_VENTA_OK, RES_BAJA_VENTA_KO,

	MODIFICAR_VENTA, RES_MODIFICAR_VENTA_OK, RES_MODIFICAR_VENTA_KO,

	BUSCAR_VENTA, RES_BUSCAR_VENTA_OK, RES_BUSCAR_VENTA_KO,

	MOSTRAR_TODAS_VENTAS, RES_MOSTRAR_TODAS_VENTAS_OK, RES_MOSTRAR_TODAS_VENTAS_KO,

	MOSTRAR_VENTAS_POR_EMPLEADO, RES_MOSTRAR_VENTAS_POR_EMPLEADO_OK, RES_MOSTRAR_VENTAS_POR_EMPLEADO_KO,

	MOSTRAR_VENTAS_POR_CLIENTE, RES_MOSTRAR_VENTAS_POR_CLIENTE_OK, RES_MOSTRAR_VENTAS_POR_CLIENTE_KO,

}