package presentacion.GUI;

public enum Evento {

	// -------------------------------------// VISTA PRINCIPAL
	// -------------------------------------//
	VISTA_PRINCIPAL,

	// -------------------------------------// EMPLEADO
	// -------------------------------------//

	// PRINCIPAL
	EMPLEADO,

	// ALTA EMPLEADO
	ALTA_EMPLEADO, RES_ALTA_EMPLEADO_OK, RES_ALTA_EMPLEADO_KO,

	// BAJA EMPLEADO
	BAJA_EMPLEADO, RES_BAJA_EMPLEADO_OK, RES_BAJA_EMPLEADO_KO,

	// MODIFICAR EMPLEADO
	MODIFICAR_EMPLEADO, RES_MODIFICAR_EMPLEADO_OK, RES_MODIFICAR_EMPLEADO_KO,

	// BUSCAR EMPLEADO
	BUSCAR_EMPLEADO, RES_BUSCAR_EMPLEADO_OK, RES_BUSCAR_EMPLEADO_KO,

	// MOSTRAR TODOS LOS EMPLEADOS
	MOSTRAR_TODOS_EMPLEADOS, RES_MOSTRAR_TODOS_EMPLEADOS_OK, RES_MOSTRAR_TODOS_EMPLEADOS_KO,

	// CONSULTA: EMPLEADO CON MÁS VENTAS
	CALCULAR_MAS_VENDIDO, RES_CALCULAR_MAS_VENDIDO_OK, RES_CALCULAR_MAS_VENDIDO_KO,

	// VISTAS DE EMPLEADO
	VALTA_EMPLEADO, VBAJA_EMPLEADO, VMODIFICAR_EMPLEADO, VBUSCAR_EMPLEADO, VMOSTRAR_TODOS_EMPLEADOS,
	VCALCULAR_MAS_VENDIDO,

	// -------------------------------------// CLIENTE
	// -------------------------------------//

	CLIENTE,

	ALTA_CLIENTE, RES_ALTA_CLIENTE_OK, RES_ALTA_CLIENTE_KO,

	BAJA_CLIENTE, RES_BAJA_CLIENTE_OK, RES_BAJA_CLIENTE_KO,

	MODIFICAR_CLIENTE, RES_MODIFICAR_CLIENTE_OK, RES_MODIFICAR_CLIENTE_KO,

	BUSCAR_CLIENTE, RES_BUSCAR_CLIENTE_OK, RES_BUSCAR_CLIENTE_KO,

	MOSTRAR_TODOS_CLIENTES, RES_MOSTRAR_TODOS_CLIENTES_OK, RES_MOSTRAR_TODOS_CLIENTES_KO,

	// VISTAS DE CLIENTE
	VALTA_CLIENTE, VBAJA_CLIENTE, VMODIFICAR_CLIENTE, VBUSCAR_CLIENTE, VMOSTRAR_TODOS_CLIENTES,

	// -------------------------------------// ALMACÉN
	// -------------------------------------//

	ALMACEN,

	ALTA_ALMACEN, RES_ALTA_ALMACEN_OK, RES_ALTA_ALMACEN_KO,

	BAJA_ALMACEN, RES_BAJA_ALMACEN_OK, RES_BAJA_ALMACEN_KO,

	MODIFICAR_ALMACEN, RES_MODIFICAR_ALMACEN_OK, RES_MODIFICAR_ALMACEN_KO,

	BUSCAR_ALMACEN, RES_BUSCAR_ALMACEN_OK, RES_BUSCAR_ALMACEN_KO,

	MOSTRAR_TODOS_ALMACENES, RES_MOSTRAR_TODOS_ALMACENES_OK, RES_MOSTRAR_TODOS_ALMACENES_KO,

	// VISTAS DE ALMACÉN
	VALTA_ALMACEN, VBAJA_ALMACEN, VMODIFICAR_ALMACEN, VBUSCAR_ALMACEN, VMOSTRAR_TODOS_ALMACENES,

	// -------------------------------------// PROVEEDOR
	// -------------------------------------//

	PROVEEDOR,

	ALTA_PROVEEDOR, RES_ALTA_PROVEEDOR_OK, RES_ALTA_PROVEEDOR_KO,

	BAJA_PROVEEDOR, RES_BAJA_PROVEEDOR_OK, RES_BAJA_PROVEEDOR_KO,

	MODIFICAR_PROVEEDOR, RES_MODIFICAR_PROVEEDOR_OK, RES_MODIFICAR_PROVEEDOR_KO,

	BUSCAR_PROVEEDOR, RES_BUSCAR_PROVEEDOR_OK, RES_BUSCAR_PROVEEDOR_KO,

	MOSTRAR_TODOS_PROVEEDORES, RES_MOSTRAR_TODOS_PROVEEDORES_OK, RES_MOSTRAR_TODOS_PROVEEDORES_KO,

	MOSTRAR_PROVEEDORES_POR_PRODUCTO, RES_MOSTRAR_PROVEEDORES_POR_PRODUCTO_OK, RES_MOSTRAR_PROVEEDORES_POR_PRODUCTO_KO,

	VINCULAR_PRODUCTO_PROVEEDOR, RES_VINCULAR_PRODUCTO_PROVEEDOR_OK, RES_VINCULAR_PRODUCTO_PROVEEDOR_KO,

	DESVINCULAR_PRODUCTO_PROVEEDOR, RES_DESVINCULAR_PRODUCTO_PROVEEDOR_OK, RES_DESVINCULAR_PRODUCTO_PROVEEDOR_KO,

	// consulta
	PROVEEDOR_CON_MAS_UDS, RES_PROVEEDOR_CON_MAS_UDS_OK, RES_PROVEEDOR_CON_MAS_UDS_KO,

	// VISTAS DE PROVEEDOR
	VALTA_PROVEEDOR, VBAJA_PROVEEDOR, VMODIFICAR_PROVEEDOR, VBUSCAR_PROVEEDOR, VMOSTRAR_TODOS_PROVEEDORES,
	VMOSTRAR_PROVEEDORES_POR_PRODUCTO, VVINCULAR_PRODUCTO_PROVEEDOR, VDESVINCULAR_PRODUCTO_PROVEEDOR,
	VPROVEEDOR_CON_MAS_UDS,

	// -------------------------------------// PRODUCTO
	// -------------------------------------//

	PRODUCTO,

	ALTA_PRODUCTO, RES_ALTA_PRODUCTO_OK, RES_ALTA_PRODUCTO_KO,

	BAJA_PRODUCTO, RES_BAJA_PRODUCTO_OK, RES_BAJA_PRODUCTO_KO,

	MODIFICAR_PRODUCTO, RES_MODIFICAR_PRODUCTO_OK, RES_MODIFICAR_PRODUCTO_KO,

	BUSCAR_PRODUCTO, RES_BUSCAR_PRODUCTO_OK, RES_BUSCAR_PRODUCTO_KO,

	MOSTRAR_TODOS_PRODUCTOS, RES_MOSTRAR_TODOS_PRODUCTOS_OK, RES_MOSTRAR_TODOS_PRODUCTOS_KO,

	MOSTRAR_PRODUCTOS_POR_PROVEEDOR, RES_MOSTRAR_PRODUCTOS_POR_PROVEEDOR_OK, RES_MOSTRAR_PRODUCTOS_POR_PROVEEDOR_KO,

	MOSTRAR_PRODUCTOS_POR_ALMACEN, RES_MOSTRAR_PRODUCTOS_POR_ALMACEN_OK, RES_MOSTRAR_PRODUCTOS_POR_ALMACEN_KO,

	// VISTAS DE PRODUCTO
	VALTA_PRODUCTO, VBAJA_PRODUCTO, VMODIFICAR_PRODUCTO, VBUSCAR_PRODUCTO, VMOSTRAR_TODOS_PRODUCTOS,
	VMOSTRAR_PRODUCTOS_POR_PROVEEDOR, VMOSTRAR_PRODUCTOS_POR_ALMACEN,

	// -------------------------------------// VENTA
	// -------------------------------------//

	VENTA,

	ABRIR_VENTA, RES_ABRIR_VENTA_OK, RES_ABRIR_VENTA_KO,

	CERRAR_VENTA, RES_CERRAR_VENTA_OK, RES_CERRAR_VENTA_KO,

	INSERTAR_PRODUCTO_VENTA, RES_INSERTAR_PRODUCTO_VENTA_OK, RES_INSERTAR_PRODUCTO_VENTA_KO,

	QUITAR_PRODUCTO_VENTA, RES_QUITAR_PRODUCTO_VENTA_OK, RES_QUITAR_PRODUCTO_VENTA_KO,

	BAJA_VENTA, RES_BAJA_VENTA_OK, RES_BAJA_VENTA_KO,

	MODIFICAR_VENTA, RES_MODIFICAR_VENTA_OK, RES_MODIFICAR_VENTA_KO,

	BUSCAR_VENTA, RES_BUSCAR_VENTA_OK, RES_BUSCAR_VENTA_KO,

	MOSTRAR_TODAS_VENTAS, RES_MOSTRAR_TODAS_VENTAS_OK, RES_MOSTRAR_TODAS_VENTAS_KO,

	MOSTRAR_VENTAS_POR_EMPLEADO, RES_MOSTRAR_VENTAS_POR_EMPLEADO_OK, RES_MOSTRAR_VENTAS_POR_EMPLEADO_KO,

	MOSTRAR_VENTAS_POR_CLIENTE, RES_MOSTRAR_VENTAS_POR_CLIENTE_OK, RES_MOSTRAR_VENTAS_POR_CLIENTE_KO,

	DEVOLVER_VENTA, RES_DEVOLVER_VENTA_OK, RES_DEVOLVER_VENTA_KO,

	PASAR_CARRITO_A_CERRAR, RES_PASAR_CARRITO_A_CERRAR_OK, RES_PASAR_CARRITO_A_CERRAR_KO,

	PASAR_CARRITO_A_ELIMINAR, RES_PASAR_CARRITO_A_ELIMINAR_OK, RES_PASAR_CARRITO_A_ELIMINAR_KO,

	PASAR_CARRITO_A_INSERTAR, RES_PASAR_CARRITO_A_INSERTAR_OK, RES_PASAR_CARRITO_A_INSERTAR_KO,

	// VISTAS DE VENTA
	VABRIR_VENTA, VCERRAR_VENTA, VINSERTAR_PRODUCTO_VENTA, VQUITAR_PRODUCTO_VENTA, VBAJA_VENTA, VMODIFICAR_VENTA,
	VBUSCAR_VENTA, VMOSTRAR_TODAS_VENTAS, VMOSTRAR_VENTAS_POR_EMPLEADO, VMOSTRAR_VENTAS_POR_CLIENTE, VDEVOLVER_VENTA,

	// ===========================
//  TRANSPORTE
//===========================

//PRINCIPAL
	TRANSPORTE,

//------- ALTA TRANSPORTE -------
	ALTA_TRANSPORTE, RES_ALTA_TRANSPORTE_OK, RES_ALTA_TRANSPORTE_KO,

//------- BAJA TRANSPORTE -------
	BAJA_TRANSPORTE, RES_BAJA_TRANSPORTE_OK, RES_BAJA_TRANSPORTE_KO,

//------- MODIFICAR TRANSPORTE -------
	MODIFICAR_TRANSPORTE, RES_MODIFICAR_TRANSPORTE_OK, RES_MODIFICAR_TRANSPORTE_KO,

//------- BUSCAR TRANSPORTE -------
	BUSCAR_TRANSPORTE, RES_BUSCAR_TRANSPORTE_OK, RES_BUSCAR_TRANSPORTE_KO,

//------- MOSTRAR TODOS LOS TRANSPORTES -------
	MOSTRAR_TODOS_TRANSPORTES, RES_MOSTRAR_TODOS_TRANSPORTES_OK, RES_MOSTRAR_TODOS_TRANSPORTES_KO,

//------- VINCULAR TRANSPORTE - TRABAJADOR -------
	VINCULAR_TRANSPORTE_TRABAJADOR, RES_VINCULAR_TRANSPORTE_TRABAJADOR_OK, RES_VINCULAR_TRANSPORTE_TRABAJADOR_KO,

//------- DESVINCULAR TRANSPORTE - TRABAJADOR -------
	DESVINCULAR_TRANSPORTE_TRABAJADOR, RES_DESVINCULAR_TRANSPORTE_TRABAJADOR_OK,
	RES_DESVINCULAR_TRANSPORTE_TRABAJADOR_KO,

//------- VER TRANSPORTES POR TRABAJADAOR -------
	VER_TRANSPORTE_POR_TRABAJADOR, RES_VER_TRANSPORTE_POR_TRABAJADOR_OK, RES_VER_TRANSPORTE_POR_TRABAJADOR_KO,

//========================================
//    VISTAS DE TRANSPORTE
//========================================

	VALTA_TRANSPORTE, VBAJA_TRANSPORTE, VMODIFICAR_TRANSPORTE, VBUSCAR_TRANSPORTE, VMOSTRAR_TODOS_TRANSPORTES,
	VVINCULAR_TRANSPORTE_TRABAJADOR, VDESVINCULAR_TRANSPORTE_TRABAJADOR, VVER_TRANSPORTE_POR_TRABAJADOR,

// ===========================
//  PAQUETE
//===========================

//PRINCIPAL
	PAQUETE,

//ALTA
	ALTA_PAQUETE, RES_ALTA_PAQUETE_OK, RES_ALTA_PAQUETE_KO,

//BAJA
	BAJA_PAQUETE, RES_BAJA_PAQUETE_OK, RES_BAJA_PAQUETE_KO,

//MODIFICAR
	MODIFICAR_PAQUETE, RES_MODIFICAR_PAQUETE_OK, RES_MODIFICAR_PAQUETE_KO,

//BUSCAR
	BUSCAR_PAQUETE, RES_BUSCAR_PAQUETE_OK, RES_BUSCAR_PAQUETE_KO,

//MOSTRAR TODOS
	MOSTRAR_TODOS_PAQUETES, RES_MOSTRAR_TODOS_PAQUETES_OK, RES_MOSTRAR_TODOS_PAQUETES_KO,
	
// MOSTRAR POR FACTURA
	VER_PAQUETES_POR_FACTURA, RES_VER_PAQUETES_POR_FACTURA_OK, RES_VER_PAQUETES_POR_FACTURA_KO,

// MOSTRAR POR RUTA
	VER_PAQUETES_POR_RUTA, RES_VER_PAQUETES_POR_RUTA_OK, RES_VER_PAQUETES_POR_RUTA_KO,

//VISTAS
	VALTA_PAQUETE, VBAJA_PAQUETE, VMODIFICAR_PAQUETE, VBUSCAR_PAQUETE, VMOSTRAR_TODOS_PAQUETES, VMOSTRAR_PAQUETES_POR_FACTURA,VMOSTRAR_PAQUETES_POR_RUTA,

//===========================
//  REMITENTE
//===========================

//PRINCIPAL
	REMITENTE,

//ALTA
	ALTA_REMITENTE, RES_ALTA_REMITENTE_OK, RES_ALTA_REMITENTE_KO,

//BAJA
	BAJA_REMITENTE, RES_BAJA_REMITENTE_OK, RES_BAJA_REMITENTE_KO,

//MODIFICAR
	MODIFICAR_REMITENTE, RES_MODIFICAR_REMITENTE_OK, RES_MODIFICAR_REMITENTE_KO,

//BUSCAR
	BUSCAR_REMITENTE, RES_BUSCAR_REMITENTE_OK, RES_BUSCAR_REMITENTE_KO,

//MOSTRAR TODOS
	MOSTRAR_TODOS_REMITENTES, RES_MOSTRAR_TODOS_REMITENTES_OK, RES_MOSTRAR_TODOS_REMITENTES_KO,

//CALCULAR PRECIO PAQUETES
	CALCULAR_PRECIO_PAQUETES, RES_CALCULAR_PRECIO_PAQUETES_OK, RES_CALCULAR_PRECIO_PAQUETES_KO,

//VISTAS
	VALTA_REMITENTE, VBAJA_REMITENTE, VMODIFICAR_REMITENTE, VBUSCAR_REMITENTE, VMOSTRAR_TODOS_REMITENTES,
	VCALCULAR_PRECIO_PAQUETES,

//===========================
//  FACTURA
//===========================

	// ===========================
	// ======== FACTURA ==========
	// ===========================

	// PRINCIPAL
	FACTURA,

	// ALTA / ABRIR
	ABRIR_FACTURA, RES_ABRIR_FACTURA_OK, RES_ABRIR_FACTURA_KO,

	// BAJA / CERRAR
	CERRAR_FACTURA, RES_CERRAR_FACTURA_OK, RES_CERRAR_FACTURA_KO,

	// iNSERTAR PAQUETE A FACTURA
	INSERTAR_PAQUETE_FACTURA, RES_INSERTAR_PAQUETE_FACTURA_OK, RES_INSERTAR_PAQUETE_FACTURA_KO,

	// QUITAR PAQUETE DE FACTURA

	QUITAR_PAQUETE_FACTURA, RES_QUITAR_PAQUETE_FACTURA_OK, RES_QUITAR_PAQUETE_FACTURA_KO,

	// MODIFICAR
	MODIFICAR_FACTURA, RES_MODIFICAR_FACTURA_OK, RES_MODIFICAR_FACTURA_KO,

	// BUSCAR
	BUSCAR_FACTURA, RES_BUSCAR_FACTURA_OK, RES_BUSCAR_FACTURA_KO,

	// MOSTRAR TODAS
	MOSTRAR_TODAS_FACTURAS, RES_MOSTRAR_TODAS_FACTURAS_OK, RES_MOSTRAR_TODAS_FACTURAS_KO,

	VER_FACTURAS_POR_REMITENTE, RES_VER_FACTURAS_POR_REMITENTE_OK, RES_VER_FACTURAS_POR_REMITENTE_KO,
	
	//DEVOLUCION
	DEVOLUCION, RES_DEVOLUCION_OK, RES_DEVOLUCION_KO,
	
	//PASAR CARRITOFACTURA
	PASAR_CARRITOFACTURA_A_CERRAR, RES_PASAR_CARRITOFACTURA_A_CERRAR_OK, RES_PASAR_CARRITOFACTURA_A_CERRAR_KO,

	PASAR_CARRITOFACTURA_A_ELIMINAR, RES_PASAR_CARRITOFACTURA_A_ELIMINAR_OK, RES_PASAR_CARRITOFACTURA_A_ELIMINAR_KO,

	PASAR_CARRITOFACTURA_A_INSERTAR, RES_PASAR_CARRITOFACTURA_A_INSERTAR_OK, RES_PASAR_CARRITOFACTURA_A_INSERTAR_KO,

	// ===========================
	// ======== VISTAS ===========
	// ===========================
	VABRIR_FACTURA, VCERRAR_FACTURA, VINSERTAR_PAQUETE_FACTURA, VQUITAR_PAQUETE_FACTURA, VMODIFICAR_FACTURA,
	VBUSCAR_FACTURA, VMOSTRAR_TODAS_FACTURAS, VVER_FACTURAS_POR_REMITENTE, VDEVOLUCION,

//===========================
//  RUTA
//===========================

//PRINCIPAL
	RUTA,

//ALTA
	ALTA_RUTA, RES_ALTA_RUTA_OK, RES_ALTA_RUTA_KO,

//BAJA
	BAJA_RUTA, RES_BAJA_RUTA_OK, RES_BAJA_RUTA_KO,

//MODIFICAR
	MODIFICAR_RUTA, RES_MODIFICAR_RUTA_OK, RES_MODIFICAR_RUTA_KO,

//BUSCAR
	BUSCAR_RUTA, RES_BUSCAR_RUTA_OK, RES_BUSCAR_RUTA_KO,

//MOSTRAR TODAS
	MOSTRAR_TODAS_RUTAS, RES_MOSTRAR_TODAS_RUTAS_OK, RES_MOSTRAR_TODAS_RUTAS_KO,

// RELACIÓN TRABAJADOR – RUTA
	VINCULAR_RUTA_TRABAJADOR, RES_VINCULAR_RUTA_TRABAJADOR_OK, RES_VINCULAR_RUTA_TRABAJADOR_KO,
	DESVINCULAR_RUTA_TRABAJADOR, RES_DESVINCULAR_RUTA_TRABAJADOR_OK, RES_DESVINCULAR_RUTA_TRABAJADOR_KO,

// VER RUTAS POR TRABAJADOR
	VER_RUTA_POR_TRABAJADOR, RES_VER_RUTA_POR_TRABAJADOR_OK, RES_VER_RUTA_POR_TRABAJADOR_KO,
//VISTAS
	VALTA_RUTA, VBAJA_RUTA, VMODIFICAR_RUTA, VBUSCAR_RUTA, VMOSTRAR_TODAS_RUTAS, VAVINCULAR_RUTA_TRABAJADOR,
	VDESVINCULAR_RUTA_TRABAJADOR, VVER_RUTA_POR_TRABAJADOR,

//===========================
//  TRABAJADOR
//===========================

//PRINCIPAL
	TRABAJADOR,

//ALTA
	ALTA_TRABAJADOR, RES_ALTA_TRABAJADOR_OK, RES_ALTA_TRABAJADOR_KO,

//BAJA
	BAJA_TRABAJADOR, RES_BAJA_TRABAJADOR_OK, RES_BAJA_TRABAJADOR_KO,

//MODIFICAR
	MODIFICAR_TRABAJADOR, RES_MODIFICAR_TRABAJADOR_OK, RES_MODIFICAR_TRABAJADOR_KO,

//BUSCAR
	BUSCAR_TRABAJADOR, RES_BUSCAR_TRABAJADOR_OK, RES_BUSCAR_TRABAJADOR_KO,

//MOSTRAR TODOS
	MOSTRAR_TODOS_TRABAJADORES, RES_MOSTRAR_TODOS_TRABAJADORES_OK, RES_MOSTRAR_TODOS_TRABAJADORES_KO,
	
//MOSTRAR POR TRNASPORTE
	MOSTRAR_TRABAJADOR_POR_TRANSPORTE, RES_MOSTRAR_TRABAJADOR_POR_TRANSPORTE_OK, RES_MOSTRAR_TRABAJADOR_POR_TRANSPORTE_KO,

// RELACIÓN TRABAJADOR – TRANSPORTE
	//VER_TRABAJADOR_POR_TRANSPORTE, RES_VER_TRABAJADOR_POR_TRANSPORTE_OK, RES_VER_TRABAJADOR_POR_TRANSPORTE_KO,
// RELACIÓN TRABAJADOR – RUTA
	VER_TRABAJADOR_POR_RUTA, RES_VER_TRABAJADOR_POR_RUTA_OK, RES_VER_TRABAJADOR_POR_RUTA_KO,

//VISTAS
	VALTA_TRABAJADOR, VBAJA_TRABAJADOR, VMODIFICAR_TRABAJADOR, VBUSCAR_TRABAJADOR, VMOSTRAR_TODOS_TRABAJADORES,
	VVER_TRABAJADOR_POR_TRANSPORTE, VVER_TRABAJADOR_POR_RUTA;
}
