package presentacion.factoria;

import presentacion.vista.IGUI;
import presentacion.vista.almacen.GUIAlmacen;
import presentacion.vista.cliente.GUICliente;
import presentacion.vista.empleado.GUIEmpleado;
import presentacion.vista.producto.GUIProducto;
import presentacion.vista.proveedor.GUIProveedor;
import presentacion.vista.venta.GUIVenta;

public class FactoriaPresentacionImp extends FactoriaPresentacion {
	
	@Override
	public IGUI GeneraVista(Evento e) {
		switch (e) {

		  // EMPLEADO
        case ALTA_EMPLEADO: case RES_ALTA_EMPLEADO_OK: case RES_ALTA_EMPLEADO_KO:
        case BAJA_EMPLEADO: case RES_BAJA_EMPLEADO_OK: case RES_BAJA_EMPLEADO_KO:
        case MODIFICAR_EMPLEADO: case RES_MODIFICAR_EMPLEADO_OK: case RES_MODIFICAR_EMPLEADO_KO:
        case BUSCAR_EMPLEADO: case RES_BUSCAR_EMPLEADO_OK: case RES_BUSCAR_EMPLEADO_KO:
        case MOSTRAR_TODOS_EMPLEADOS: case RES_MOSTRAR_TODOS_EMPLEADOS_OK: case RES_MOSTRAR_TODOS_EMPLEADOS_KO:
            return new GUIEmpleado();

        // CLIENTE
        case ALTA_CLIENTE: case RES_ALTA_CLIENTE_OK: case RES_ALTA_CLIENTE_KO:
        case BAJA_CLIENTE: case RES_BAJA_CLIENTE_OK: case RES_BAJA_CLIENTE_KO:
        case MODIFICAR_CLIENTE: case RES_MODIFICAR_CLIENTE_OK: case RES_MODIFICAR_CLIENTE_KO:
        case BUSCAR_CLIENTE: case RES_BUSCAR_CLIENTE_OK: case RES_BUSCAR_CLIENTE_KO:
        case MOSTRAR_TODOS_CLIENTES: case RES_MOSTRAR_TODOS_CLIENTES_OK: case RES_MOSTRAR_TODOS_CLIENTES_KO:
            return new GUICliente();

        // ALMACEN
        case ALTA_ALMACEN: case RES_ALTA_ALMACEN_OK: case RES_ALTA_ALMACEN_KO:
        case BAJA_ALMACEN: case RES_BAJA_ALMACEN_OK: case RES_BAJA_ALMACEN_KO:
        case MODIFICAR_ALMACEN: case RES_MODIFICAR_ALMACEN_OK: case RES_MODIFICAR_ALMACEN_KO:
        case BUSCAR_ALMACEN: case RES_BUSCAR_ALMACEN_OK: case RES_BUSCAR_ALMACEN_KO:
        case MOSTRAR_TODOS_ALMACENES: case RES_MOSTRAR_TODOS_ALMACENES_OK: case RES_MOSTRAR_TODOS_ALMACENES_KO:
            return new GUIAlmacen();

        // PROVEEDOR
        case ALTA_PROVEEDOR: case RES_ALTA_PROVEEDOR_OK: case RES_ALTA_PROVEEDOR_KO:
        case BAJA_PROVEEDOR: case RES_BAJA_PROVEEDOR_OK: case RES_BAJA_PROVEEDOR_KO:
        case MODIFICAR_PROVEEDOR: case RES_MODIFICAR_PROVEEDOR_OK: case RES_MODIFICAR_PROVEEDOR_KO:
        case BUSCAR_PROVEEDOR: case RES_BUSCAR_PROVEEDOR_OK: case RES_BUSCAR_PROVEEDOR_KO:
        case MOSTRAR_TODOS_PROVEEDORES: case RES_MOSTRAR_TODOS_PROVEEDORES_OK: case RES_MOSTRAR_TODOS_PROVEEDORES_KO:
        case MOSTRAR_PROVEEDORES_POR_PRODUCTO: case RES_MOSTRAR_PROVEEDORES_POR_PRODUCTO_OK: case RES_MOSTRAR_PROVEEDORES_POR_PRODUCTO_KO:
        case VINCULAR_PRODUCTO_PROVEEDOR: case RES_VINCULAR_PRODUCTO_PROVEEDOR_OK: case RES_VINCULAR_PRODUCTO_PROVEEDOR_KO:
        case DESVINCULAR_PRODUCTO_PROVEEDOR: case RES_DESVINCULAR_PRODUCTO_PROVEEDOR_OK: case RES_DESVINCULAR_PRODUCTO_PROVEEDOR_KO:
            return new GUIProveedor();

        // PRODUCTO
        case ALTA_PRODUCTO: case RES_ALTA_PRODUCTO_OK: case RES_ALTA_PRODUCTO_KO:
        case BAJA_PRODUCTO: case RES_BAJA_PRODUCTO_OK: case RES_BAJA_PRODUCTO_KO:
        case MODIFICAR_PRODUCTO: case RES_MODIFICAR_PRODUCTO_OK: case RES_MODIFICAR_PRODUCTO_KO:
        case BUSCAR_PRODUCTO: case RES_BUSCAR_PRODUCTO_OK: case RES_BUSCAR_PRODUCTO_KO:
        case MOSTRAR_TODOS_PRODUCTOS: case RES_MOSTRAR_TODOS_PRODUCTOS_OK: case RES_MOSTRAR_TODOS_PRODUCTOS_KO:
        case MOSTRAR_PRODUCTOS_POR_PROVEEDOR: case RES_MOSTRAR_PRODUCTOS_POR_PROVEEDOR_OK: case RES_MOSTRAR_PRODUCTOS_POR_PROVEEDOR_KO:
        case MOSTRAR_PRODUCTOS_POR_ALMACEN: case RES_MOSTRAR_PRODUCTOS_POR_ALMACEN_OK: case RES_MOSTRAR_PRODUCTOS_POR_ALMACEN_KO:
            return new GUIProducto();

        // VENTA
        case ABRIR_VENTA: case RES_ABRIR_VENTA_OK: case RES_ABRIR_VENTA_KO:
        case CERRAR_VENTA: case RES_CERRAR_VENTA_OK: case RES_CERRAR_VENTA_KO:
        case INSERTAR_PRODUCTO_VENTA: case RES_INSERTAR_PRODUCTO_VENTA_OK: case RES_INSERTAR_PRODUCTO_VENTA_KO:
        case QUITAR_PRODUCTO_VENTA: case RES_QUITAR_PRODUCTO_VENTA_OK: case RES_QUITAR_PRODUCTO_VENTA_KO:
        case BAJA_VENTA: case RES_BAJA_VENTA_OK: case RES_BAJA_VENTA_KO:
        case MODIFICAR_VENTA: case RES_MODIFICAR_VENTA_OK: case RES_MODIFICAR_VENTA_KO:
        case BUSCAR_VENTA: case RES_BUSCAR_VENTA_OK: case RES_BUSCAR_VENTA_KO:
        case MOSTRAR_TODAS_VENTAS: case RES_MOSTRAR_TODAS_VENTAS_OK: case RES_MOSTRAR_TODAS_VENTAS_KO:
        case MOSTRAR_VENTAS_POR_EMPLEADO: case RES_MOSTRAR_VENTAS_POR_EMPLEADO_OK: case RES_MOSTRAR_VENTAS_POR_EMPLEADO_KO:
        case MOSTRAR_VENTAS_POR_CLIENTE: case RES_MOSTRAR_VENTAS_POR_CLIENTE_OK: case RES_MOSTRAR_VENTAS_POR_CLIENTE_KO:
        case DEVOLVER_VENTA: case RES_DEVOLVER_VENTA_OK: case RES_DEVOLVER_VENTA_KO:
            return new GUIVenta();

        default:
            return null;
		}
	}

}
